language: node_js
node_js:
  - "7"
before_script:
  - npm install -g gulp-cli
script:
  - gulp
cache:
  directories:
    - "node_modules"
    - "bower_components"
deploy:
  provider: pages
  local_dir: dist
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep-history: true
  commit_message: "[AUTO BUILD] `date +'%Y-%m-%d %T (%:z)'`"
  repo: allanim/allanim.github.io
  target-branch: master
  on:
    branch: master